# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: rust:1.28.0

before_script:
  - cargo version

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# https://gitlab.com/gitlab-org/gitlab-ce/issues/12963
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - target/

stages:
  - build
  - test

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test
