unstable_features = true
indent_style = "Block"
reorder_imports = false
match_block_trailing_comma = true
use_field_init_shorthand = true
match_arm_blocks = false
blank_lines_upper_bound = 1
use_small_heuristics = true
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
tab_spaces = 4
max_width = 80
# fn_args_density = "Compressed"